runtime: python39

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 5
  max_instances: 500
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
